services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./cleanny:/cleanny
    environment:
      - DB_HOST=database
      - DB_NAME=postgresdb
      - DB_USER=postgresuser
      - DB_PASS=postgrespass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database
      
  database:
    image: postgres:alpine3.18
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespass