# Generated by Django 4.2.11 on 2024-04-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=100, verbose_name='Имя клиента')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='Фамилия клиента')),
                ('surname', models.CharField(help_text='Введите Отчество', max_length=100, verbose_name='Отчество клиента')),
                ('email', models.CharField(help_text='Введите email', max_length=100, verbose_name='Email клиента')),
                ('tel', models.IntegerField(help_text='Введите номер телефона с кодом', verbose_name='Номер клиента')),
                ('street', models.CharField(help_text='Введите улицу', max_length=100, verbose_name='Улица клиента')),
                ('housing', models.CharField(blank=True, help_text='Введите корпус', max_length=100, null=True, verbose_name='Корпус клиента')),
                ('home', models.CharField(help_text='Введите номер дома', max_length=100, verbose_name='Номер дома клиента')),
                ('flat', models.CharField(help_text='Введите номер квартиры', max_length=100, verbose_name='Номер квартиры клиента')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='images', verbose_name='Фото клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя сотрудника', max_length=100, verbose_name='Имя сотрудника')),
                ('last_name', models.CharField(help_text='Введите фамилию сотрудника', max_length=100, verbose_name='Фамилия сотрудника')),
                ('email', models.CharField(help_text='Введите email сотрудника', max_length=100, verbose_name='Email сотрудника')),
                ('photo', models.ImageField(help_text='Загрузите фото сотрудника', upload_to='images', verbose_name='Фото сотрудника')),
            ],
        ),
    ]
