# Generated by Django 4.2.11 on 2024-04-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_worker_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='media/images', verbose_name='Фото клиента'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(help_text='Загрузите фото сотрудника', upload_to='media/images', verbose_name='Фото сотрудника'),
        ),
    ]
