# Generated by Django 4.2.11 on 2024-04-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_client_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='comments',
        ),
    ]
