# Generated by Django 4.2.11 on 2024-04-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_client_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название услуги', max_length=100, verbose_name='Название услуги')),
                ('cost', models.IntegerField(help_text='Введите стоимость улуги', verbose_name='Стоимость услуги')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text='Введите email', max_length=100, verbose_name='Email клиента'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_time', models.DateTimeField(help_text='Введите дату и время уборки', verbose_name='Дата и время уборки')),
                ('discount', models.IntegerField(blank=True, choices=[(0, '1 раз или первый раз'), (7, 'раз в месяц 7%'), (10, 'раз в две недели 10%'), (15, 'раз в неделю 15%')], default=0, help_text='Выберите переодичность уборки', verbose_name='Переодичность уборки со скидкой')),
                ('client', models.ForeignKey(help_text='Введите свои данные', on_delete=django.db.models.deletion.CASCADE, to='service.client', verbose_name='Данные клиента')),
                ('services', models.ForeignKey(help_text='Выберите услуги', on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Услуга')),
            ],
        ),
    ]
