# Generated by Django 4.2.11 on 2024-04-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_service_alter_client_email_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=1, help_text='Введите email', max_length=100, verbose_name='Email клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=1, help_text='Введите имя', max_length=100, verbose_name='Имя клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='flat',
            field=models.CharField(default=1, help_text='Введите номер квартиры', max_length=100, verbose_name='Номер квартиры клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='home',
            field=models.CharField(default=1, help_text='Введите номер дома', max_length=100, verbose_name='Номер дома клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='housing',
            field=models.CharField(blank=True, help_text='Введите корпус', max_length=100, null=True, verbose_name='Корпус клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=1, help_text='Введите фамилию', max_length=100, verbose_name='Фамилия клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='images', verbose_name='Фото клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default=1, help_text='Введите улицу', max_length=100, verbose_name='Улица клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default=1, help_text='Введите Отчество', max_length=100, verbose_name='Отчество клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tel',
            field=models.IntegerField(default=1, help_text='Введите номер телефона с кодом', verbose_name='Номер клиента'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
